### ISSUE TITLE
横向滚动无效

### ISSUE THREAD

**Issue by WangShuXian6** [huangjincq/vue-better-scroll#35]
```html
<div class="test">
      <vue-better-scroll class=""
                         :stopPropagation="false"
                         direction="horizontal"
      >
        <div class="min">
          <div
              class="image-wrapper"
              v-for="(pen,index) in penList"
              :key="pen.name"
          >
          </div>
        </div>

      </vue-better-scroll>
    </div>
```

```css
.test {
      position: fixed;
      top: 0;
      left: 0;
      width: 100vw;
      height: 100px;
      background-color: #ff9e39;
      .min{
        display: flex;
        .image-wrapper {
          display: flex;
          width: 50px;
          height: 50px;
          background-color: white;
          margin-right: 10px;
        }
      }

    }
```
